<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #333;
            padding-bottom: 8px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header .date {
            color: #666;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
            font-weight: bold;
            font-size: 9px;
        }
        td {
            border: 1px solid #dee2e6;
            padding: 6px;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 20px;
            text-align: right;
            color: #666;
            font-size: 8px;
        }
        .total-row {
            background-color: #e9ecef !important;
            font-weight: bold;
        }
        .logo {
            text-align: center;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="logo">
        <h2 style="margin: 0; color: #333;">ImpactGuru CRM</h2>
    </div>
    
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="date">Generated on: {{ $date }}</div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th width="5%">ID</th>
                <th width="20%">Name</th>
                <th width="20%">Email</th>
                <th width="15%">Phone</th>
                <th width="10%">Orders</th>
                <th width="15%">Created By</th>
                <th width="15%">Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($customers as $customer)
            <tr>
                <td>{{ $customer->id }}</td>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->email }}</td>
                <td>{{ $customer->phone ?? 'N/A' }}</td>
                <td>{{ $customer->orders_count }}</td>
                <td>{{ $customer->creator->name ?? 'N/A' }}</td>
                <td>{{ $customer->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @endforeach
            
            @if($customers->count() > 0)
            <tr class="total-row">
                <td colspan="4">Total Customers: {{ $customers->count() }}</td>
                <td>Total Orders: {{ $customers->sum('orders_count') }}</td>
                <td colspan="2"></td>
            </tr>
            @endif
        </tbody>
    </table>
    
    <div class="footer">
        Page 1 of 1 | Generated by ImpactGuru CRM
    </div>
</body>
</html>