<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #333;
            padding-bottom: 8px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header .date {
            color: #666;
            font-size: 12px;
        }
        .filters {
            margin-bottom: 10px;
            padding: 5px;
            background-color: #f8f9fa;
            border-radius: 4px;
        }
        .filters span {
            margin-right: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
            font-weight: bold;
            font-size: 9px;
        }
        td {
            border: 1px solid #dee2e6;
            padding: 6px;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .status-pending { color: #ffc107; font-weight: bold; }
        .status-processing { color: #17a2b8; font-weight: bold; }
        .status-completed { color: #28a745; font-weight: bold; }
        .status-cancelled { color: #dc3545; font-weight: bold; }
        .footer {
            margin-top: 20px;
            text-align: right;
            color: #666;
            font-size: 8px;
        }
        .total-row {
            background-color: #e9ecef !important;
            font-weight: bold;
        }
        .summary {
            margin-bottom: 10px;
            padding: 8px;
            background-color: #f8f9fa;
            border-radius: 4px;
            font-size: 9px;
        }
        .summary span {
            margin-right: 15px;
        }
        .amount {
            text-align: right;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="date">Generated on: {{ $date }}</div>
    </div>
    
    @if($statusFilter || $startDate)
    <div class="filters">
        <strong>Filters Applied:</strong>
        @if($statusFilter && $statusFilter != 'All')
            <span>Status: {{ ucfirst($statusFilter) }}</span>
        @endif
        @if($startDate && $endDate)
            <span>Date Range: {{ $startDate }} to {{ $endDate }}</span>
        @endif
    </div>
    @endif
    
    <div class="summary">
        <span>Total Orders: {{ $totalOrders }}</span>
        <span>Pending: {{ $pendingCount }}</span>
        <span>Completed: {{ $completedCount }}</span>
        <span style="float: right;">Total Amount: ${{ number_format($totalAmount, 2) }}</span>
    </div>
    
    <table>
        <thead>
            <tr>
                <th width="10%">Order #</th>
                <th width="20%">Customer</th>
                <th width="15%">Email</th>
                <th width="8%">Amount</th>
                <th width="10%">Status</th>
                <th width="10%">Order Date</th>
                <th width="20%">Notes</th>
                <th width="12%">Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>{{ $order->order_number }}</td>
                <td>{{ $order->customer->name }}</td>
                <td>{{ $order->customer->email }}</td>
                <td class="amount">${{ number_format($order->amount, 2) }}</td>
                <td class="status-{{ $order->status }}">
                    {{ ucfirst($order->status) }}
                </td>
                <td>{{ $order->order_date }}</td>
                <td>{{ Str::limit($order->notes, 50) ?: 'N/A' }}</td>
                <td>{{ $order->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @endforeach
            
            @if($orders->count() > 0)
            <tr class="total-row">
                <td colspan="3">Summary</td>
                <td class="amount">${{ number_format($totalAmount, 2) }}</td>
                <td>Total: {{ $totalOrders }}</td>
                <td colspan="3">
                    Pending: {{ $pendingCount }} | 
                    Completed: {{ $completedCount }}
                </td>
            </tr>
            @endif
        </tbody>
    </table>
    
    <div class="footer">
        Page 1 of 1 | Generated by ImpactGuru CRM
    </div>
</body>
</html>